import 'fake-indexeddb/auto';
import { beforeEach, describe, expect, it } from 'vitest';
import { deleteProjectCascade, getScreenshot, importExtensionSnapshot, listProjects, listSessions, listSteps, newId, openEvidenceDb, saveProject, saveSession, saveStep, type EvidenceProject, type EvidenceSession, type EvidenceStep } from '../web/src/core/modules/evidenceStore';

beforeEach(async()=>{const db=await openEvidenceDb();for(const name of ['projects','sessions','steps','screenshots','settings'])await new Promise<void>((resolve,reject)=>{const tx=db.transaction(name,'readwrite');tx.objectStore(name).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});localStorage.clear();});
function records(){const now=Date.now();const project:EvidenceProject={id:newId(),name:'QA',feature:'Login',environment:'HML',version:'1',responsible:'Felipe',date:'2026-08-13',browser:'Chrome',expectedResult:'OK',overallResult:'',createdAt:now,updatedAt:now};const session:EvidenceSession={id:newId(),projectId:project.id,name:'Sessão',state:'recording',createdAt:now,updatedAt:now};const step:EvidenceStep={id:newId(),sessionId:session.id,projectId:project.id,sequence:1,title:'Entrar',action:'Clicar',element:'button',description:'Clicar no botão “Entrar”.',expectedResult:'OK',actualResult:'',status:'not-run',url:'https://example.com',timestamp:now,screenshotId:newId()};return{project,session,step};}
describe('IndexedDB do painel',()=>{
 it('cria e recupera projeto, sessão, passo e imagem',async()=>{const r=records();await saveProject(r.project);await saveSession(r.session);await saveStep(r.step,new Blob(['image'],{type:'image/png'}));expect(await listProjects()).toHaveLength(1);expect(await listSessions(r.project.id)).toHaveLength(1);expect(await listSteps(r.session.id)).toHaveLength(1);expect(await getScreenshot(r.step.screenshotId)).not.toBeNull();});
 it('atualiza e ordena passos',async()=>{const r=records();await saveProject(r.project);await saveSession(r.session);await saveStep({...r.step,sequence:2});await saveStep({...r.step,id:newId(),screenshotId:null,sequence:1});expect((await listSteps(r.session.id)).map(s=>s.sequence)).toEqual([1,2]);});
 it('exclui projeto em cascata',async()=>{const r=records();await saveProject(r.project);await saveSession(r.session);await saveStep(r.step,new Blob(['x']));await deleteProjectCascade(r.project.id);expect(await listProjects()).toHaveLength(0);expect(await listSessions(r.project.id)).toHaveLength(0);expect(await listSteps(r.session.id)).toHaveLength(0);});
 it('sincroniza projeto, sessão, passo e screenshot da extensão',async()=>{
  const now=Date.now();
  const result=await importExtensionSnapshot({schema:'homolog-backup',schemaVersion:1,projects:[{projectId:'p1',name:'Gravação',createdAt:now,updatedAt:now}],sessions:[{sessionId:'s1',projectId:'p1',name:'Sessão gravada',state:'recording',createdAt:now,updatedAt:now}],steps:[{stepId:'st1',sessionId:'s1',projectId:'p1',sequence:1,actionType:'click',target:{tagName:'BUTTON',visibleText:'Entrar'},description:'Clicar no botão “Entrar”.',url:'https://example.com',timestamp:now,viewportPoint:{x:10,y:20}}],screenshotsMeta:[{screenshotId:'shot1',stepId:'st1',sessionId:'s1',projectId:'p1',imageDataUrl:'data:image/png;base64,aW1hZ2U='}]});
  expect(result.steps).toBe(1);expect((await listProjects())[0].name).toBe('Gravação');expect((await listSessions('p1'))[0].id).toBe('s1');const step=(await listSteps('s1'))[0];expect(step.element).toBe('Entrar');expect((await getScreenshot(step.screenshotId))?.type).toBe('image/png');
 });
});
